version: '3'

services:

  calculate-this:
    image: bash-calculator-api:yeah-thats-right---didnt-think-id-do-it
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8080:8080'